export const
	APP_SET_THEME = 'APP_SET_THEME',
	APP_RESTART = 'APP_RESTART',
	APP_SET_LAST_TAB = 'APP_SET_LAST_TAB',

	APP_SET_SWIAPEABLES = 'APP_SET_SWIAPEABLES',

	APP_DISABLE_SCROLL = 'APP_DISABLE_SCROLL',

	APP_SET_BROWSER = 'APP_SET_BROWSER'