require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

target 'rn3' do
    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])
    use_flipper!
end

target 'extension' do
    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])
end

# Custom configuration
post_install do |installer|
    # Enables Flipper.
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
        # Fix App extension warnings
        target.build_configurations.each do |config|
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
end