update_fastlane

platform :ios do
  # iOS Lanes

  desc 'Fetch certificates and provisioning profiles.'
  lane :certificates do
    match(app_identifier: 'io.raindrop.raindropio', type: 'development', readonly: is_ci)
    match(app_identifier: 'io.raindrop.raindropio', type: 'appstore', readonly: is_ci)
  end

  desc 'Build the iOS application.'
  lane :build do
    certificates
    increment_build_number(xcodeproj: 'ios/rn3.xcodeproj')
    gym(scheme: 'rn3', workspace: 'ios/rn3.xcworkspace', include_bitcode: false)
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    upload_to_testflight(username: "jakie.future@gmail.com", skip_waiting_for_build_processing: true)
  end
end

platform :android do
  # Android Lanes

  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Google Play Beta.'
  lane :beta do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    upload_to_play_store(track: 'beta')
  end
end
