export { default as Home } from './home'
export { default as Login } from './login'
export { default as Register } from './register'
export { default as JWT } from './jwt'
export { default as TFA } from './tfa'
export { default as Native } from './native'